sudo: required
language: ruby

services:
- docker

before_install:
- make build

script:
- make test

deploy:
  provider: deis
  controller: deis.ngra.ps.nginxlab.com
  app: album-manager
  cli_version: 1.11.2
  username: deploymentuser
  password: deployment
  on:
    repo: nginxinc/ngra-album-manager
