source 'http://rubygems.org'

gem 'sinatra'
gem 'activerecord', '~> 4.2.7.1'
gem 'sinatra-activerecord'
gem 'sinatra-reloader'
gem 'json'
gem 'newrelic_rpm'
gem 'httparty'
gem 'rake'

group :development, :test do
  gem 'better_errors'
  gem 'sqlite3'
  gem 'mysql2'
end

group :test do
  gem 'database_cleaner'
  gem 'factory_bot'
  gem 'rspec'
  gem 'rack-test'
end

group :production do
  gem 'mysql2'
  gem 'unicorn'
end
