name: album-manager
resolver:
  host: kube-dns.kube-system.svc.cluster.local
  ttl: 3s
external_domain_name: k8s.mra.nginxps.com
internal_domain_name: svc.cluster.local
namespace: nginx-mra
root: /usr/src/app/public
oss_extension: .oss
log_to_syslog : false
syslog_error_log_location: "syslog:server=localhost:5544 debug"
error_log_location: "/var/log/nginx/error_log debug"
service_log_name: album_manager_mra
syslog_access_log_location: "syslog:server=localhost:5544,facility=local6,tag=album_manager_mra,severity=info json"
access_log_location: "/var/log/nginx/access_log combined"
services:
  uploader:
    server: nginx-mra.svc.cluster.local
    service: service=_https._tcp.photouploader
    expose_external: true
    healthcheck: true
    oss_port: 12006
