name: album-manager
resolver:
  host: 127.0.0.11
  ttl: 3s
root: /usr/src/app/public
log_to_syslog : false
syslog_error_log_location: "syslog:server=localhost:5544 debug"
error_log_location: "/var/log/nginx/error_log debug"
service_log_name: album_manager_mra
syslog_access_log_location: "syslog:server=localhost:5544,facility=local6,tag=album_manager_mra,severity=info json"
access_log_location: "/var/log/nginx/access_log combined"
services:
  uploader:
    server: ''
    expose_external: true
    healthcheck: false
    port: 84
