name: album-manager
resolver:
  host: 198.51.100.1 198.51.100.2 198.51.100.3
  ttl: 3s
root: /usr/src/app/public
oss_extension: .oss
services:
  uploader:
    server: marathon.mesos
    service: service=_uploader._tcp
    expose_external: true
    healthcheck: true
    oss_port: 12006
